<?php

return [
    'api/data/diva_stock' => [
        'refresh_frequency' => 'daily',
        'all_frequencies' => ['daily'],
        'keys' => [
            [
                'variable_key' => 'Qtte',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-313'],
            ],
            [
                'variable_key' => 'qtteReservee',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-313'],
            ],
            [
                'variable_key' => 'Qtte',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-314'],
            ],
            [
                'variable_key' => 'qtteReservee',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-314'],
            ],
            [
                'variable_key' => 'Qtte',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-315'],
            ],
            [
                'variable_key' => 'qtteReservee',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-315'],
            ],
        ],
    ],
    'api/data/expeditions' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'DatEExpedition',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-308'],
            ],
        ],
    ],
    'api/data/losttype' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'LostTypeDesc',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-207'],
            ],
        ],
    ],
    'api/data/mp' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Description',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-215'],
            ],
        ],
    ],
    'api/data/ofabrication' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'IDArticle',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-214'],
            ],
            [
                'variable_key' => 'IDOFabrication',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-301'],
            ],
            [
                'variable_key' => 'OFAbrication',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-301'],
            ],
            [
                'variable_key' => 'IDOFabrication',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-302'],
            ],
            [
                'variable_key' => 'Quantite',
                'variable_type' => 'Complex',
                'is_filtered' => true,
                'filter_key' => 'IDArticle',
                'filter_value' => null,
                'has_function' => true,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-303'],
            ],
            [
                'variable_key' => 'DtDebut',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-306'],
            ],
            [
                'variable_key' => 'DtFin',
                'variable_type' => 'Complex',
                'is_filtered' => true,
                'filter_key' => 'IDOFabrication',
                'filter_value' => null,
                'has_function' => true,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-307'],
            ],
            [
                'variable_key' => 'Quantite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-307'],
            ],
        ],
    ],
    'api/data/production' => [
        'refresh_frequency' => 'daily',
        'all_frequencies' => ['daily'],
        'keys' => [
            [
                'variable_key' => 'ClockTime',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-218'],
            ],
        ],
    ],
    'api/data/q/articles_sans_mouvement_durant_365_jours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Qtte_SansMvt_365j',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-319'],
            ],
            [
                'variable_key' => 'Qtte_SansMvt_365j',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-320'],
            ],
            [
                'variable_key' => 'Qtte_SansMvt_365j',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-321'],
            ],
        ],
    ],
    'api/data/q/capacite_de_stockage_en_nombre_de_conteneurs' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Total_Conteneurs',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-323'],
            ],
            [
                'variable_key' => 'Total_Conteneurs',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-324'],
            ],
        ],
    ],
    'api/data/q/colis_total_3var' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant', 'daily'],
        'keys' => [
            [
                'variable_key' => 'Total_rejetes',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-102'],
            ],
            [
                'variable_key' => 'Total_colis',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-102'],
            ],
            [
                'variable_key' => 'Total_rejetes',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-103'],
            ],
            [
                'variable_key' => 'Colis_annules',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-103'],
            ],
            [
                'variable_key' => 'Total_rejetes',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-120'],
            ],
            [
                'variable_key' => 'Total_colis',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-120'],
            ],
            [
                'variable_key' => 'Colis_annules',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-121'],
            ],
        ],
    ],
    'api/data/q/efficience_chaine' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'TempsStandard',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-204'],
            ],
            [
                'variable_key' => 'TempsStandard',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-211'],
            ],
        ],
    ],
    'api/data/q/etat_avancement' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'engagement',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-336'],
            ],
        ],
    ],
    'api/data/q/inspections_paquet_annee_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'BundleInspectedYear',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-107'],
            ],
        ],
    ],
    'api/data/q/inspections_paquet_jour_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'BundleInspectedToday',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-106'],
            ],
        ],
    ],
    'api/data/q/lost_time' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'TotalLostTime',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-207'],
            ],
        ],
    ],
    'api/data/q/minutes_presence' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'TempsPresence_Min',
                'variable_type' => 'Complex',
                'is_filtered' => true,
                'filter_key' => 'ProdGroup',
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-201'],
            ],
            [
                'variable_key' => 'TempsPresence_Min',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-202'],
            ],
            [
                'variable_key' => 'TempsPresence_Min',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-203'],
            ],
            [
                'variable_key' => 'TempsPresence_Min',
                'variable_type' => 'Complex',
                'is_filtered' => true,
                'filter_key' => 'ProdGroup',
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-204'],
            ],
            [
                'variable_key' => 'TempsPresence_Min',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-208'],
            ],
            [
                'variable_key' => 'TempsPresence_Min',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-209'],
            ],
            [
                'variable_key' => 'TempsPresence_Min',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-210'],
            ],
        ],
    ],
    'api/data/q/minutes_produites' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'MinuteProduite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-201'],
            ],
            [
                'variable_key' => 'MinuteProduite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-203'],
            ],
            [
                'variable_key' => 'MinuteProduite',
                'variable_type' => 'Complex',
                'is_filtered' => true,
                'filter_key' => 'EmployeeName',
                'filter_value' => null,
                'has_function' => true,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-208'],
            ],
            [
                'variable_key' => 'MinuteProduite',
                'variable_type' => 'Complex',
                'is_filtered' => true,
                'filter_key' => 'EmployeeName',
                'filter_value' => null,
                'has_function' => true,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-209'],
            ],
        ],
    ],
    'api/data/q/moyenne_date_de_transfert_date_de_reservation' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'MoyenneJours',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-328'],
            ],
            [
                'variable_key' => 'MoyenneJours',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-329'],
            ],
            [
                'variable_key' => 'MoyenneJours',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-330'],
            ],
        ],
    ],
    'api/data/q/nombre_d_ofs_livres_avec_date_de_transfert_coupe_coupe_jemmel' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'NbOF_Livres_Total',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-325'],
            ],
            [
                'variable_key' => 'NbOF_Livres_Total',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-326'],
            ],
            [
                'variable_key' => 'OF_AvecTransfertCoupeJemmel',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-326'],
            ],
            [
                'variable_key' => 'NbOF_Livres_Total',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-327'],
            ],
            [
                'variable_key' => 'OF_AvecTransfertCoupeJemmel',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-327'],
            ],
        ],
    ],
    'api/data/q/nombre_de_rouleaux' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'NbRouleaux',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-323'],
            ],
            [
                'variable_key' => 'NbRouleaux',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-324'],
            ],
        ],
    ],
    'api/data/q/pieces_ok_de_premier_coup_annee_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'FirstPassYear',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-105'],
            ],
        ],
    ],
    'api/data/q/pieces_ok_de_premier_coup_jour_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'FirstPassToday',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-104'],
            ],
        ],
    ],
    'api/data/q/pieces_produites_annee_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'ProducedYear',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-105'],
            ],
        ],
    ],
    'api/data/q/pieces_produites_jour_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'ProducedToday',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-104'],
            ],
        ],
    ],
    'api/data/q/qte_depart_chaine_article_of' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Departage',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-206'],
            ],
        ],
    ],
    'api/data/q/qte_engagement' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Engagement',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-310'],
            ],
            [
                'variable_key' => 'Quantite_Engagement',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-311'],
            ],
            [
                'variable_key' => 'Quantite_Engagement',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-334'],
            ],
            [
                'variable_key' => 'Quantite_Engagement',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-335'],
            ],
        ],
    ],
    'api/data/q/qte_entree_serigraphie' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Entree_Serigraphie',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-309'],
            ],
        ],
    ],
    'api/data/q/qte_produite' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Produite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-202'],
            ],
            [
                'variable_key' => 'Quantite_Produite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-204'],
            ],
            [
                'variable_key' => 'Quantite_Produite',
                'variable_type' => 'Complex',
                'is_filtered' => true,
                'filter_key' => 'OF_No',
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-309'],
            ],
        ],
    ],
    'api/data/q/qte_produite_indiv_jour' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Produite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-210'],
            ],
        ],
    ],
    'api/data/q/quantite_par_famille' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'FamilleFG',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-333'],
            ],
            [
                'variable_key' => 'Quantite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-333'],
            ],
        ],
    ],
    'api/data/q/quantite_par_provenance_total' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Provenance',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-332'],
            ],
            [
                'variable_key' => 'Quantite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-332'],
            ],
        ],
    ],
    'api/data/q/quantite_par_typologie_fournitures' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Typologie',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-331'],
            ],
            [
                'variable_key' => 'Quantite',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-331'],
            ],
        ],
    ],
    'api/data/q/quantite_totale_du_stock' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Totale_Stock',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-319'],
            ],
            [
                'variable_key' => 'Quantite_Totale_Stock',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-320'],
            ],
            [
                'variable_key' => 'Quantite_Totale_Stock',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-321'],
            ],
        ],
    ],
    'api/data/q/rejets_suite_inspection_paquet_annee_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'BundleRejectYear',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-107'],
            ],
        ],
    ],
    'api/data/q/rejets_suite_inspection_paquet_jour_en_cours' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'BundleRejectToday',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-106'],
            ],
        ],
    ],
    'api/data/q/sortie_coupe' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Sortie_Coupe',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-206'],
            ],
            [
                'variable_key' => 'Quantite_Sortie_Coupe',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-311'],
            ],
        ],
    ],
    'api/data/q/sortie_serigraphie' => [
        'refresh_frequency' => 'daily',
        'all_frequencies' => ['daily'],
        'keys' => [
            [
                'variable_key' => 'Quantite_Sortie_Serigraphie',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-217'],
            ],
        ],
    ],
    'api/data/q/stock_moyen' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'StockMoyen',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-316'],
            ],
            [
                'variable_key' => 'StockMoyen',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-317'],
            ],
            [
                'variable_key' => 'StockMoyen',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-318'],
            ],
        ],
    ],
    'api/data/q/taging_reel' => [
        'refresh_frequency' => 'daily',
        'all_frequencies' => ['daily'],
        'keys' => [
            [
                'variable_key' => 'StatutTagging',
                'variable_type' => 'Direct',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'daily',
                'kpis' => ['F-REQ-217'],
            ],
        ],
    ],
    'api/data/q/temps_operation' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'TempsOperation',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-210'],
            ],
        ],
    ],
    'api/data/vwdefect' => [
        'refresh_frequency' => 'instant',
        'all_frequencies' => ['instant'],
        'keys' => [
            [
                'variable_key' => 'DefectQty',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-116'],
            ],
            [
                'variable_key' => 'QCCheckpointQty',
                'variable_type' => 'Complex',
                'is_filtered' => false,
                'filter_key' => null,
                'filter_value' => null,
                'has_function' => false,
                'fn' => 'Latest',
                'refresh_frequency' => 'instant',
                'kpis' => ['F-REQ-117'],
            ],
        ],
    ],
];
