// Barrel: re-exports every public name of the original `@/lib/pbi/model` path.
// Splitting `model.ts` into a folder of cohesive modules while keeping the
// import path `@/lib/pbi/model` (→ `model/index.ts`) intact.

export type {
    Agg,
    AnalyticsKind,
    AnalyticsLine,
    AxisDef,
    AxisPosition,
    AxisStyle,
    BarStyle,
    BarsApplyMode,
    CalloutStyle,
    CategoryLabelStyle,
    CfAgg,
    CfBound,
    CfBoundType,
    CfComparator,
    CfRule,
    CfRuleCondition,
    CfStyle,
    CfValueType,
    ConditionalFormat,
    CrossFilter,
    DataLabelContent,
    DataLabelPosition,
    DataLabelSeriesOverride,
    DataLabelStyle,
    DisplayUnit,
    EvalCtx,
    Field,
    FieldReference,
    FieldType,
    FontStyle,
    FxFormat,
    FxOp,
    FxRule,
    GaugeBoundStyle,
    GaugeDataLabelsStyle,
    GaugeLabelStyle,
    GaugeStyle,
    GridlinesStyle,
    GridlineStyle,
    Interaction,
    LegendPosition,
    LegendStyle,
    ListMeasureImpl,
    MeasureEvalError,
    MeasureImpl,
    MeasureValidation,
    NumberFormat,
    Page,
    PageFormat,
    PlotAreaStyle,
    Row,
    ScatterPoint,
    SeriesMeta,
    TableDef,
    TableNumberStyle,
    TitleStyle,
    ValueAggregationMode,
    ValueFormat,
    Visual,
    VisualType,
    WellField,
} from './types';

export {
    ANALYTICS_DEFAULT_COLOR,
    ANALYTICS_KINDS,
    CF_AGGS,
    CF_BOUND_TYPES,
    CF_COMPARATORS,
    CF_RULE_CONDITIONS,
    CF_STYLES,
    CF_VALUE_TYPES,
    DISPLAY_UNITS,
    isDisplayUnit,
    isNumberFormat,
    isValueAggregationMode,
    LIST_AGG_NUMERIC_MODES,
    NUMBER_FORMATS,
    PAGE_PRESETS,
    VALUE_AGGREGATION_MODES,
} from './consts';

export {
    fieldType,
    findTableForField,
    hasColumn,
    isMeasure,
    LIST_MEASURE_IMPL,
    MEASURE_IMPL,
    setTables,
    TABLES,
} from './state';

export {
    isListMeasure,
    listAggIgnoredCount,
    listMeasureValue,
    listTreatment,
} from './aggregate';

export {
    applyFx,
    axisPositionDefault,
    defaultAxes,
    lockedPctAxis,
    DEFAULT_AXES,
    defaultConditionalFormat,
    defaultGaugeStyle,
    DEFAULT_AXIS_STYLE,
    DEFAULT_BAR_STYLE,
    DEFAULT_CALLOUT,
    DEFAULT_CATEGORY_LABEL,
    DEFAULT_DATA_LABELS,
    DEFAULT_GAUGE,
    DEFAULT_GAUGE_BOUND,
    DEFAULT_GAUGE_DATA_LABELS,
    DEFAULT_GAUGE_LABEL,
    DEFAULT_GRIDLINES,
    DEFAULT_LEGEND,
    DEFAULT_PLOT_AREA,
    DEFAULT_TABLE_NUMBER,
    DEFAULT_TITLE_STYLE,
    fieldIssue,
    fieldLabel,
    fieldNumericIssue,
    formatAxisDefTick,
    formatCallout,
    formatDisplayUnitValue,
    formatNumber,
    formatNumberPattern,
    formatNumberWith,
    formatTableNumber,
    formatTableTreated,
    formatValue,
    formatWellValue,
    inferFieldType,
    isTableNumberCustomized,
    measureLabel,
    normalizeAxisStyle,
    normalizeAxes,
    normalizeBarStyle,
    normalizeCalloutStyle,
    normalizeCategoryLabelStyle,
    normalizeConditionalFormat,
    normalizeDataLabelStyle,
    normalizeFontStyle,
    normalizeFxFormat,
    normalizeGaugeStyle,
    normalizeGridlinesStyle,
    normalizeLegendStyle,
    normalizePlotAreaStyle,
    normalizeTableNumber,
    normalizeTitleStyle,
    normalizeValueFormat,
    normalizeWellField,
    parseFieldReference,
    singleValueLabel,
    visualTitleStyle,
    wellForReference,
    conditionalFormatFromFx,
    STACKED_EMPTY_FILL,
} from './format';

export {
    aggregate,
    buildChartData,
    buildParetoData,
    buildScatterData,
    buildTableCells,
    compileListMeasure,
    compileMeasure,
    distinctValues,
    evaluateMeasure,
    gaugeBoundValue,
    isSlicerVisual,
    listMeasureSource,
    measureColumnRefs,
    measureError,
    MEASURE_ERRORS,
    parseDaxRef,
    registerMeasure,
    scopedRows,
    singleValue,
    unregisterMeasure,
    validateMeasureExpression,
    visualTable,
} from './engine';